version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'website'
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/buscar_trampo'
      - box:/box

  website:
    depends_on:
      - "postgres"
      - 'redis'
      - 'elasticsearch'

    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/buscar_trampo
      - box:/box
    environment:
      - ELASTICSEARCH_HOST=elasticsearch

volumes:
  elasticsearch:
  redis:
  postgres:
  box: